# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 66fd52c
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: fane.shala@epfl.ch
author_name: Fane Shala
github_org: faneshala
package_name: chembalancer
project_name: ChemBalancer
short_description: Chemical equation Balancer
